import React from 'react';
import Modal from '../common/Modal';
import { Download, Printer, FileText, CheckCircle, Truck, AlertTriangle, ShieldCheck, ArrowRight } from 'lucide-react';
import { numberToIndianWords } from '../../screens/SalesScreen';

export default function DocumentPreviewModal({ isOpen, onClose, doc, onNotify }) {
  if (!isOpen || !doc) return null;

  const docId = doc.id || doc.poNumber || doc.piNumber || doc.ewbNumber || doc.estimateNo || 'DOC-2026-0001';
  const isPO = doc.id?.startsWith('PO') || !!doc.poNumber || doc.type === 'Purchase Order' || doc.documentType === 'Purchase Order';
  const isPI = doc.id?.startsWith('PI') || !!doc.piNumber || doc.type === 'Proforma Invoice' || doc.documentType === 'Proforma Invoice';
  const isEWB = doc.id?.startsWith('EWB') || !!doc.ewbNumber || doc.type === 'E-Way Bill' || doc.documentType === 'E-Way Bill';
  const isInvoice = !isPO && !isPI && !isEWB && (doc.id?.startsWith('INV') || doc.type === 'Tax Invoice' || doc.documentType === 'Tax Invoice');

  // Customer or Supplier details
  const partyName = isPO 
    ? (doc.supplier || 'Supplier Organization') 
    : (doc.customer || doc.customerFullName || 'Customer Organization');
  
  const partyContact = isPO 
    ? (doc.supplierContact || 'Procurement In-charge')
    : (doc.customerContact || doc.contactPerson || 'Procurement Officer');

  const partyAddress = isPO
    ? (doc.supplierAddress || 'Vendor Industrial Zone, Pune, Maharashtra')
    : (doc.billingAddress || doc.customerAddress || 'Customer Plant, Industrial Area, Maharashtra');

  const partyGstin = isPO
    ? (doc.supplierGstin || '27AAACS4821M1ZB')
    : (doc.customerGstin || doc.gstin || '27AAACT2718E1ZQ');

  const dateStr = doc.date || doc.invoiceDate || '09-09-2026';
  const placeOfSupply = doc.placeOfSupply || doc.customerState || '27-Maharashtra';
  const refOrder = doc.salesOrder || doc.refOrder || doc.challanNo || 'SO-2026-0142';

  // Normalize items
  let items = [];
  if (doc.items && doc.items.length > 0) {
    items = doc.items;
  } else if (doc.goods && doc.goods.length > 0) {
    items = doc.goods.map(g => ({
      name: g.product,
      desc: g.product,
      hsn: g.hsn || '84669390',
      qty: g.quantity || 1,
      unit: g.unit || 'Unit',
      unitPrice: g.taxableValue / (g.quantity || 1),
      total: g.taxableValue,
      gst: g.gstRate || 18
    }));
  } else {
    items = [
      { 
        id: 1, 
        name: doc.spindleModel || 'GPS-HSK-A63-24K Precision Motorized Spindle Unit (15 kW, 24,000 RPM)', 
        desc: doc.spindleModel || 'GPS-HSK-A63-24K Precision Motorized Spindle Unit (15 kW, 24,000 RPM)',
        hsn: '84669390', 
        qty: 2, 
        unitPrice: 421000, 
        total: 842000 
      }
    ];
  }

  // Calculate totals
  const subtotal = doc.taxableValue || doc.subtotal || (typeof doc.amount === 'number' ? doc.amount : 842000);
  const discount = doc.discount || 0;
  const taxRate = doc.taxRate || 18;
  const cgst = doc.cgstAmount || 0;
  const sgst = doc.sgstAmount || 0;
  const igst = doc.igstAmount || 0;
  const taxAmount = (cgst + sgst + igst) || doc.gstAmount || Math.round((subtotal - discount) * (taxRate / 100));
  const grandTotal = doc.totalInvoiceValue || doc.totalAmount || ((subtotal - discount) + taxAmount);
  const amountInWords = doc.amountInWords || numberToIndianWords(grandTotal);

  const handleDownload = () => {
    if (onNotify) {
      onNotify(`Generated and downloaded official ${docId}.pdf successfully.`);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const getDocTitle = () => {
    if (isPO) return 'PURCHASE ORDER';
    if (isPI) return 'PROFORMA INVOICE';
    if (isEWB) return 'e-WAY BILL (PART-A & PART-B)';
    if (isInvoice) return 'TAX INVOICE';
    return 'COMMERCIAL ESTIMATE';
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Document Preview: ${docId}.pdf`}
      maxWidth="860px"
      footer={
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
            Official electronic document generated by GPS Spindle ERP Core
            {isEWB && <span style={{ color: '#b45309', fontWeight: 600, marginLeft: '6px' }}>• Internal Demo Prototype</span>}
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Close
            </button>
            <button type="button" className="btn btn-secondary" onClick={handleDownload}>
              <Download size={13} />
              <span>Download PDF</span>
            </button>
            <button type="button" className="btn btn-primary" onClick={handlePrint}>
              <Printer size={13} />
              <span>Print Document</span>
            </button>
          </div>
        </div>
      }
    >
      <div style={{ 
        background: '#ffffff', 
        color: '#0f172a', 
        fontFamily: 'Inter, system-ui, sans-serif', 
        padding: '24px 28px', 
        borderRadius: 'var(--radius-sm)',
        border: '1px solid var(--border-color)',
        boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
        fontSize: '11.5px',
        lineHeight: 1.4
      }}>
        {/* Prototype Watermark / Banner if E-Way Bill */}
        {isEWB && (
          <div style={{ 
            background: '#FFF6DD', 
            border: '1px solid #FDE68A', 
            borderRadius: '4px', 
            padding: '6px 12px', 
            marginBottom: '14px', 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'space-between',
            color: '#B7791F'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: 700 }}>
              <AlertTriangle size={14} />
              <span>DEMO / INTERNAL PROTOTYPE E-WAY BILL</span>
            </div>
            <span style={{ fontSize: '10.5px' }}>Not connected to National Informatics Centre (NIC) / GSTN Portal</span>
          </div>
        )}

        {/* Document Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #7A1F3D', paddingBottom: '16px', marginBottom: '16px' }}>
          <div style={{ display: 'flex', gap: '14px', alignItems: 'center' }}>
            <div style={{ 
              width: '56px', 
              height: '56px', 
              border: '1px solid var(--border-color)', 
              borderRadius: '6px', 
              padding: '3px',
              display: 'flex', 
              alignItems: 'center', 
              justifyContent: 'center',
              background: '#ffffff'
            }}>
              <img src="/logo.jpg" alt="GPS Spindle" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} />
            </div>
            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 800, color: 'var(--text-main)', letterSpacing: '-0.01em', margin: 0 }}>
                GENERAL PRECISION SPINDLES PVT. LTD.
              </h2>
              <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '2px' }}>
                Manufacturer of High-Precision Motorized & Belt-Driven Spindles • ISO 9001:2015 Certified
              </div>
              <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                Plot B-12, Nanded City Industrial Complex, Pune - 411041, Maharashtra, India
              </div>
              <div style={{ fontSize: '10.5px', color: '#7A1F3D', fontWeight: 600 }}>
                GSTIN: 27AABCG1492K1Z8 • MSME: MH26A0189736 • sales@gpsspindle.com
              </div>
            </div>
          </div>

          <div style={{ textAlign: 'right' }}>
            <div style={{ 
              display: 'inline-block',
              padding: '4px 10px', 
              borderRadius: '4px', 
              background: '#F5E8ED', 
              color: '#7A1F3D', 
              fontWeight: 800, 
              fontSize: '12px',
              letterSpacing: '0.04em',
              textTransform: 'uppercase'
            }}>
              {getDocTitle()}
            </div>
            <div className="mono" style={{ fontSize: '15px', fontWeight: 800, color: 'var(--text-main)', marginTop: '6px' }}>
              {docId}
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>
              Date: <strong className="mono" style={{ color: 'var(--text-main)' }}>{dateStr}</strong>
            </div>
            {isPO && doc.expectedDelivery && (
              <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                Expected: <strong className="mono" style={{ color: '#7A1F3D' }}>{doc.expectedDelivery}</strong>
              </div>
            )}
            {isPI && doc.validUntil && (
              <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                Valid Until: <strong className="mono" style={{ color: '#9A6700' }}>{doc.validUntil}</strong>
              </div>
            )}
            {isEWB && (
              <div style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
                Valid Until: <strong className="mono" style={{ color: '#7A1F3D' }}>{doc.validUntil || '10 Sep 2026'}</strong>
              </div>
            )}
          </div>
        </div>

        {/* EWB Barcode Simulation */}
        {isEWB && (
          <div style={{ 
            display: 'flex', 
            justifyContent: 'space-between', 
            alignItems: 'center', 
            padding: '10px 14px', 
            background: '#F8FAF9', 
            border: '1px dashed #cbd5e1', 
            borderRadius: '4px', 
            marginBottom: '14px' 
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <div style={{ 
                fontFamily: 'monospace', 
                letterSpacing: '4px', 
                fontSize: '18px', 
                fontWeight: 800, 
                color: '#1e293b',
                background: '#e2e8f0',
                padding: '4px 10px',
                borderRadius: '3px'
              }}>
                ||| | |||| || ||| |||| |
              </div>
              <div>
                <div style={{ fontSize: '11px', fontWeight: 700, color: '#0f172a' }}>E-Way Bill QR & 12-Digit Verification Code</div>
                <div className="mono" style={{ fontSize: '10.5px', color: '#475569' }}>9821-4409-1284-0042 (Generated by GPS Spindle Dispatch)</div>
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <span className="badge" style={{ background: '#EAF7EE', color: '#16803C', fontWeight: 700, padding: '3px 8px' }}>
                {doc.status || 'Active'}
              </span>
            </div>
          </div>
        )}

        {/* Customer / Supplier & Commercial Info Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: '1.3fr 1fr', gap: '14px', marginBottom: '16px' }}>
          <div style={{ padding: '12px 14px', border: '1px solid var(--border-color)', borderRadius: '4px', background: 'var(--bg-surface-subtle)' }}>
            <div style={{ fontSize: '10px', fontWeight: 700, color: '#7A1F3D', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              {isPO ? 'Vendor / Supplier Information' : (isEWB ? 'Consignee / Recipient Details' : 'Billed To Client')}
            </div>
            <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text-main)', marginTop: '3px' }}>
              {partyName}
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '2px' }}>
              {partyAddress}
            </div>
            <div style={{ marginTop: '6px', fontSize: '11px', display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>GSTIN: </span>
                <strong className="mono" style={{ color: 'var(--text-main)' }}>{partyGstin}</strong>
              </div>
              {partyContact && (
                <div>
                  <span style={{ color: 'var(--text-muted)' }}>Contact: </span>
                  <strong style={{ color: 'var(--text-main)' }}>{partyContact}</strong>
                </div>
              )}
            </div>
          </div>

          <div style={{ padding: '12px 14px', border: '1px solid var(--border-color)', borderRadius: '4px', background: 'var(--bg-surface-subtle)' }}>
            <div style={{ fontSize: '10px', fontWeight: 700, color: '#7A1F3D', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              {isPO ? 'Delivery & Logistics' : (isEWB ? 'Part-B Transportation Details' : 'Commercial Reference')}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', marginTop: '4px', fontSize: '11.5px' }}>
              {isPO && (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Delivery Terms:</span>
                    <span style={{ fontWeight: 600 }}>Door Delivery (GPS Stores)</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Payment Terms:</span>
                    <span style={{ fontWeight: 600 }}>{doc.paymentTerms || 'Net 30 Days'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Delivery Bay:</span>
                    <span style={{ fontWeight: 600 }}>Bay 1 - Raw Stores</span>
                  </div>
                </>
              )}

              {isPI && (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#F5E8ED', padding: '3px 6px', borderRadius: '3px' }}>
                    <span style={{ color: '#7A1F3D', fontWeight: 700 }}>Linked Sales Order:</span>
                    <span className="mono" style={{ fontWeight: 800, color: '#7A1F3D' }}>{doc.salesOrder || 'SO-2026-041'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Payment Terms:</span>
                    <span style={{ fontWeight: 600 }}>{doc.paymentTerms || '50% Advance'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Dispatch Window:</span>
                    <span style={{ fontWeight: 600 }}>6 Weeks post-advance</span>
                  </div>
                </>
              )}

              {isEWB && (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Tax Invoice Ref:</span>
                    <span className="mono" style={{ fontWeight: 700 }}>{doc.invoice || 'INV-2026-019'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Vehicle Number:</span>
                    <span className="mono" style={{ fontWeight: 700, color: '#7A1F3D' }}>{doc.vehicle || 'MH12AB1234'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Transporter:</span>
                    <span style={{ fontWeight: 600 }}>{doc.transporter || 'ABC Logistics'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Mode & Distance:</span>
                    <span style={{ fontWeight: 600 }}>{doc.mode || 'Road'} • {doc.distance || '540 km'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)' }}>LR / Doc No:</span>
                    <span className="mono" style={{ fontWeight: 600 }}>{doc.transportDocNo || 'LR-2026-88192'}</span>
                  </div>
                </>
              )}

              {isInvoice && (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748b' }}>Reference Order:</span>
                    <span className="mono" style={{ fontWeight: 600 }}>{refOrder}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748b' }}>Payment Terms:</span>
                    <span style={{ fontWeight: 600 }}>{doc.creditTerms || 'Net 30 Days'}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748b' }}>Dispatch Mode:</span>
                    <span style={{ fontWeight: 600 }}>Door Delivery (Insured)</span>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Line Items Table */}
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '16px' }}>
          <thead>
            <tr style={{ background: '#F1F5F9', borderBottom: '2px solid #cbd5e1' }}>
              <th style={{ padding: '8px 10px', textAlign: 'left', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '35px' }}>#</th>
              <th style={{ padding: '8px 10px', textAlign: 'left', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase' }}>Description of Goods / Technical Specification</th>
              <th style={{ padding: '8px 10px', textAlign: 'center', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '70px' }}>HSN</th>
              <th style={{ padding: '8px 10px', textAlign: 'center', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '60px' }}>Qty</th>
              <th style={{ padding: '8px 10px', textAlign: 'right', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '100px' }}>Rate (₹)</th>
              <th style={{ padding: '8px 10px', textAlign: 'center', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '55px' }}>GST</th>
              <th style={{ padding: '8px 10px', textAlign: 'right', fontSize: '10.5px', fontWeight: 700, textTransform: 'uppercase', width: '110px' }}>Total (₹)</th>
            </tr>
          </thead>
          <tbody>
            {items.map((it, idx) => {
              const qty = Number(it.qty || it.quantity) || 1;
              const unit = it.unit || 'Units';
              const unitPrice = Number(it.rate || it.unitPrice) || 0;
              const lineTotal = it.total || it.totalValue || (qty * unitPrice);
              const name = it.item || it.product || it.name || it.desc || 'Precision Component';
              const desc = it.desc !== name ? it.desc : null;
              const hsn = it.hsn || '84669390';
              const gst = it.gst || it.gstRate || 18;

              return (
                <tr key={it.id || idx} style={{ borderBottom: '1px solid #e2e8f0' }}>
                  <td style={{ padding: '8px 10px', color: '#64748b', verticalAlign: 'top' }}>{idx + 1}</td>
                  <td style={{ padding: '8px 10px', verticalAlign: 'top' }}>
                    <div style={{ fontWeight: 600, color: '#0f172a' }}>{name}</div>
                    {desc && <div style={{ fontSize: '10.5px', color: '#64748b', marginTop: '2px' }}>{desc}</div>}
                  </td>
                  <td className="mono" style={{ padding: '8px 10px', textAlign: 'center', color: '#475569', verticalAlign: 'top' }}>
                    {hsn}
                  </td>
                  <td className="mono" style={{ padding: '8px 10px', textAlign: 'center', fontWeight: 600, verticalAlign: 'top' }}>
                    {qty} {unit}
                  </td>
                  <td className="mono" style={{ padding: '8px 10px', textAlign: 'right', verticalAlign: 'top' }}>
                    {unitPrice ? Math.round(unitPrice).toLocaleString('en-IN') : '-'}
                  </td>
                  <td className="mono" style={{ padding: '8px 10px', textAlign: 'center', color: '#64748b', verticalAlign: 'top' }}>
                    {gst}%
                  </td>
                  <td className="mono" style={{ padding: '8px 10px', textAlign: 'right', fontWeight: 700, color: '#0f172a', verticalAlign: 'top' }}>
                    {lineTotal ? Math.round(lineTotal).toLocaleString('en-IN') : '-'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>

        {/* Calculation Summary & Bank / Terms Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '16px', alignItems: 'flex-start' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {/* Bank details for PI and Invoices */}
            {(isPI || isInvoice) && (
              <div style={{ padding: '10px 12px', border: '1px solid var(--border-color)', borderRadius: '4px', background: 'var(--bg-surface-subtle)' }}>
                <div style={{ fontSize: '10px', fontWeight: 700, color: '#7A1F3D', textTransform: 'uppercase' }}>
                  Bank Wire Coordinates (RTGS / NEFT)
                </div>
                <div style={{ fontSize: '11px', marginTop: '4px', color: 'var(--text-main)' }}>
                  <div>Bank: <strong>ICICI BANK LIMITED, PUNE NANDED CITY</strong></div>
                  <div>Account Name: <strong>GENERAL PRECISION SPINDLES</strong></div>
                  <div>A/C Number: <strong className="mono">349105000701</strong></div>
                  <div>IFSC Code: <strong className="mono">ICIC0003491</strong></div>
                </div>
              </div>
            )}

            {/* Notes / Special Instructions */}
            <div style={{ padding: '10px 12px', border: '1px solid var(--border-color)', borderRadius: '4px', background: 'var(--bg-surface-subtle)' }}>
              <div style={{ fontSize: '10px', fontWeight: 700, color: '#7A1F3D', textTransform: 'uppercase' }}>
                {isPO ? 'Purchase Order Notes & Quality Criteria' : 'Special Terms & Notes'}
              </div>
              <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: 1.4 }}>
                {doc.notes || 'Goods subject to GPS incoming inspection. Test certificates and calibration sheets mandatory.'}
              </div>
            </div>
          </div>

          {/* Tax Calculation Card */}
          <div style={{ padding: '12px 14px', border: '1px solid var(--border-color)', borderRadius: '4px', background: '#ffffff', display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
              <span style={{ color: 'var(--text-muted)' }}>Taxable Subtotal:</span>
              <span className="mono" style={{ fontWeight: 600 }}>₹{Math.round(subtotal).toLocaleString('en-IN')}</span>
            </div>
            {discount > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: '#176B3A' }}>
                <span>Commercial Discount:</span>
                <span className="mono">-₹{Math.round(discount).toLocaleString('en-IN')}</span>
              </div>
            )}
            {cgst > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--text-muted)' }}>
                <span>Central GST (CGST 9%):</span>
                <span className="mono">₹{Math.round(cgst).toLocaleString('en-IN')}</span>
              </div>
            )}
            {sgst > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--text-muted)' }}>
                <span>State GST (SGST 9%):</span>
                <span className="mono">₹{Math.round(sgst).toLocaleString('en-IN')}</span>
              </div>
            )}
            {igst > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--text-muted)' }}>
                <span>Integrated GST (IGST 18%):</span>
                <span className="mono">₹{Math.round(igst).toLocaleString('en-IN')}</span>
              </div>
            )}
            {!cgst && !sgst && !igst && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--text-muted)' }}>
                <span>GST (18% Applicable):</span>
                <span className="mono">₹{Math.round(taxAmount).toLocaleString('en-IN')}</span>
              </div>
            )}
            <div style={{ 
              display: 'flex', 
              justifyContent: 'space-between', 
              fontSize: '14px', 
              fontWeight: 800, 
              borderTop: '2px solid #7A1F3D', 
              paddingTop: '8px', 
              marginTop: '4px',
              color: '#7A1F3D' 
            }}>
              <span>Grand Total:</span>
              <span className="mono">₹{Math.round(grandTotal).toLocaleString('en-IN')}</span>
            </div>
            <div style={{ fontSize: '10.5px', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: 1.3 }}>
              <strong>Amount in Words:</strong> {amountInWords}
            </div>
          </div>
        </div>

        {/* Signature Bar */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: '24px', paddingTop: '12px', borderTop: '1px solid var(--border-color)' }}>
          <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
            Document Ref: {docId} • Generated via GPS ERP Core on {new Date().toLocaleDateString('en-GB')}
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '11px', fontWeight: 700, color: 'var(--text-main)' }}>For GENERAL PRECISION SPINDLES PVT. LTD.</div>
            <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontStyle: 'italic', color: '#7A1F3D', fontWeight: 600 }}>
              Authorized Signatory
            </div>
            <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>Commercial Applications & Plant Operations</div>
          </div>
        </div>
      </div>
    </Modal>
  );
}
